[package]
name = "omdesk-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
omdesk-application = { path = "../omdesk-application" }
omdesk-core = { path = "../omdesk-core" }
omdesk-platform = { path = "../omdesk-platform" }
omdesk-protocol = { path = "../omdesk-protocol" }
ratatui.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
