[package]
name = "omdesky-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "omdesky"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
omdesky-application = { path = "../omdesky-application" }
omdesky-core = { path = "../omdesky-core" }
omdesky-platform = { path = "../omdesky-platform" }
omdesky-protocol = { path = "../omdesky-protocol" }
omdesky-tui = { path = "../omdesky-tui" }
rpassword.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
